// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlO6dH6lw3ZPxN2HiuU3R-Ljj8VhLDgM',
    appId: '1:1000407924192:web:b92644d24f32b8eca4bf85',
    messagingSenderId: '1000407924192',
    projectId: 'pettygramchatapp',
    authDomain: 'pettygramchatapp.firebaseapp.com',
    storageBucket: 'pettygramchatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdi7zc0hPhbdioeSop6WplZfmyhTWtSkM',
    appId: '1:1000407924192:android:2ea486faf1d6e031a4bf85',
    messagingSenderId: '1000407924192',
    projectId: 'pettygramchatapp',
    storageBucket: 'pettygramchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohrOq9QggGAZjpqE-hpDCThkn_zQtAeA',
    appId: '1:1000407924192:ios:604a3ce6a07b292ca4bf85',
    messagingSenderId: '1000407924192',
    projectId: 'pettygramchatapp',
    storageBucket: 'pettygramchatapp.appspot.com',
    iosClientId: '1000407924192-is4clb1a7vp1ef12pfphv2jul3at8rmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettygramFlutter',
  );
}
